import test from "node:test";
import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { CutsceneSchemaRegistry } from "../modules/cutscene/schemaRegistry.js";
import { CutsceneWorkspace } from "../modules/cutscene/workspace.js";
import { generateCutsceneTrigger } from "../modules/cutscene/runtime.js";
import type { CutsceneComposeSpec } from "../modules/cutscene/types.js";

test("checked-in native Cutscene is exactly generated by cutscene.compose", async () => {
  const request = JSON.parse(await fs.readFile(path.resolve("examples/cutscene/full_example/ComposeRequest.json"), "utf8")) as CutsceneComposeSpec;
  const expected = await fs.readFile(path.resolve("examples/cutscene/full_example/GeneratedNative.SC2Cutscene"), "utf8");
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "sc2-cutscene-example-"));
  const schema = await CutsceneSchemaRegistry.load();
  const workspace = new CutsceneWorkspace(root, schema);
  const result = await workspace.compose(request, { dryRun: true });
  assert.equal(result.source, expected);
  assert.equal(result.validation.valid, true);
});

test("Galaxy trigger generation is guarded by the indexed four-argument native signature", async () => {
  const schema = await CutsceneSchemaRegistry.load();
  const result = generateCutsceneTrigger(schema, {
    cutscenePath: "Cutscenes\\Intro.SC2Cutscene",
    positionExpression: "Point(0.0, 0.0)",
    playersExpression: "PlayerGroupAll()",
    autoPlay: false,
  });
  assert.match(result.source, /CutsceneCreate\("Cutscenes\\\\Intro\.SC2Cutscene", Point\(0\.0, 0\.0\), PlayerGroupAll\(\), false\);/);
  assert.equal(result.signatures.every(Boolean), true);
});

