import test from "node:test";
import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { bridgeCapabilities } from "../core/capabilities.js";
import { generateRuntimeCorpus } from "../runtime/runtimeHarness.js";
import { SchemaRegistry } from "../schema/schemaRegistry.js";
import { Workspace } from "../core/workspace.js";
import { benchmarkCodexWorkflow } from "../benchmark/codexEfficiency.js";
import { packArchive } from "../archive/archiveAdapter.js";

test("capability report never claims unconfigured runtime or packed-map support", () => {
  const oldRuntime = process.env.SC2_UI_RUNTIME_ADAPTER;
  const oldArchive = process.env.SC2_UI_ARCHIVE_ADAPTER;
  delete process.env.SC2_UI_RUNTIME_ADAPTER;
  delete process.env.SC2_UI_ARCHIVE_ADAPTER;
  try {
    const report = bridgeCapabilities("C:/Maps/Test.SC2Map");
    assert.equal(report.workspace.kind, "packed-archive-path");
    assert.equal(report.workspace.directlyEditable, false);
    assert.equal(report.runtime.actualGameValidation, false);
    assert.equal(report.archives.packedMapReadWrite, false);
  } finally {
    if (oldRuntime === undefined) delete process.env.SC2_UI_RUNTIME_ADAPTER; else process.env.SC2_UI_RUNTIME_ADAPTER = oldRuntime;
    if (oldArchive === undefined) delete process.env.SC2_UI_ARCHIVE_ADAPTER; else process.env.SC2_UI_ARCHIVE_ADAPTER = oldArchive;
  }
});

test("runtime corpus generator creates an isolated probe for every known frame type", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "sc2-ui-runtime-corpus-"));
  try {
    const schema = await SchemaRegistry.loadBundled();
    const manifest = await generateRuntimeCorpus(schema, root);
    assert.equal(manifest.frameTypes, 892);
    assert.equal(manifest.entries.length, 892);
    assert.equal(new Set(manifest.entries.map((entry) => entry.frameType.toLowerCase())).size, 892);
    const index = await fs.readFile(path.join(root, "UI", "Layout", "RuntimeCorpusIndex.SC2Layout"), "utf8");
    assert.equal((index.match(/<Include /g) ?? []).length, 892);
    assert.match(await fs.readFile(path.join(root, manifest.entries[0].file), "utf8"), /<Frame type=/);
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("Codex benchmark proves query + describe + apply workflow", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "sc2-ui-efficiency-"));
  const file = "Benchmark.SC2Layout";
  try {
    await fs.writeFile(path.join(root, file), "<?xml version=\"1.0\"?>\n<Desc>\n</Desc>\n", "utf8");
    const schema = await SchemaRegistry.loadBundled();
    const result = await benchmarkCodexWorkflow(new Workspace(root, schema), file);
    assert.deepEqual(result.transactionWorkflow.sequence, ["ui.query_frames", "ui.describe_type", "ui.apply (validation + diff included)"]);
    assert.ok(result.reductionPercent >= 70);
    assert.equal(result.validationIncludedInApply, true);
    assert.equal(result.diffIncludedInApply, true);
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("checked-in transaction example is byte-for-byte generated by ui.apply", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "sc2-ui-example-"));
  const file = "UI/Layout/TransactionDemo.SC2Layout";
  try {
    await fs.mkdir(path.dirname(path.join(root, file)), { recursive: true });
    await fs.writeFile(path.join(root, file), `<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Desc>
    <!-- Existing unknown content remains untouched. -->
    <FutureMetadata owner="user"/>
</Desc>
`, "utf8");
    const request = JSON.parse(await fs.readFile(path.resolve("examples/TransactionRequest.json"), "utf8")) as { operations: Parameters<Workspace["apply"]>[1] };
    const schema = await SchemaRegistry.loadBundled();
    const workspace = new Workspace(root, schema);
    const result = await workspace.apply(file, request.operations, { dryRun: false, stage: true, validate: true });
    assert.equal(result.validation?.valid, true);
    const expected = await fs.readFile(path.resolve("examples/TransactionDemo.SC2Layout"), "utf8");
    const actual = (await workspace.read(file)).text;
    assert.equal(actual, expected);
    assert.match(actual, /name="GameUI\/UIContainer" file="GameUI"/);
    assert.match(actual, /name="CodexButtonTemplate" template="StandardTemplates\/StandardButtonTemplate"/);
    assert.match(actual, /name="Primary" template="TransactionDemo\/CodexButtonTemplate"/);
    assert.match(actual, /<Event event="OnShown" action="Reset,Play" frame="\$this"\/>/);
    assert.match(actual, /time="0\.25" value="255"/);
    assert.match(actual, /frame="\$parent\/Secondary" enabled="False"/);
    assert.equal(
      await fs.readFile(path.resolve("examples/UI/Layout/TransactionDemo.SC2Layout"), "utf8"),
      expected,
    );
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("archive adapter packs to a temporary file and preserves a backup", async () => {
  if (process.platform === "win32") return;
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "sc2-ui-archive-"));
  try {
    const component = path.join(root, "Component");
    const archive = path.join(root, "Map.SC2Map");
    const adapter = path.join(root, "adapter.sh");
    await fs.mkdir(component);
    await fs.writeFile(path.join(component, "marker.txt"), "new", "utf8");
    await fs.writeFile(archive, "old archive", "utf8");
    await fs.writeFile(adapter, "#!/bin/sh\nif [ \"$1\" = \"pack\" ]; then printf 'packed archive' > \"$3\"; elif [ \"$1\" = \"extract\" ]; then printf 'new' > \"$3/marker.txt\"; else exit 9; fi\n", "utf8");
    await fs.chmod(adapter, 0o755);
    const result = await packArchive(component, archive, { adapter });
    assert.equal(await fs.readFile(archive, "utf8"), "packed archive");
    assert.equal(await fs.readFile(`${archive}.sc2uimcp.bak`, "utf8"), "old archive");
    assert.equal(result.backup, `${archive}.sc2uimcp.bak`);
    assert.equal(result.verification.reopened, true);
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});
