import assert from "node:assert/strict";
import {promises as fs} from "node:fs";
import os from "node:os";
import path from "node:path";
import {gunzipSync} from "node:zlib";
import test from "node:test";
import {Workspace} from "../core/workspace.js";
import {TerrainWorkspace} from "../modules/terrain/workspace.js";
import {LightingCatalog} from "../modules/terrain/lighting.js";
import {parseTerrainRecipe} from "../modules/terrain/xmlRecipe.js";
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),"sc2-lighting-"));for(const name of await fs.readdir("src/tests/fixtures/terrain-native/nydus"))await fs.writeFile(path.join(root,name.slice(0,-3)),gunzipSync(await fs.readFile(path.join("src/tests/fixtures/terrain-native/nydus",name))));await fs.mkdir(path.join(root,"Base.SC2Data/GameData"),{recursive:true});await fs.writeFile(path.join(root,"Base.SC2Data/GameData/LightData.xml"),'<Catalog><!--retain--><CLight id="Base"><ToDInfoArray AmbientColor="0.2,0.3,0.4"><Param index="HDRExposure" value="1"/><DirectionalLight index="Key"><Color value="1,1,1"/><Unknown value="keep"/></DirectionalLight></ToDInfoArray><ToDInfoArray index="1" AmbientColor="1,0,0"/></CLight></Catalog>');return {root,terrain:new TerrainWorkspace(new Workspace(root)),cleanup:()=>fs.rm(root,{recursive:true,force:true})};}
test("native City CTerrain lighting binding retains geometry and other records",async()=>{const source=await fs.readFile("src/tests/fixtures/lighting-native/City-TerrainData.xml","utf8");const catalog=new LightingCatalog(source,"CTerrain");assert.equal(catalog.list().find(n=>n.id==="Citytile")?.lighting,"Agria");assert.equal(catalog.bind("Citytile","AgriaNight"),source.replace('<Lighting value="Agria"/>','<Lighting value="AgriaNight"/>'));const light=new LightingCatalog(await fs.readFile("src/tests/fixtures/lighting-native/City-LightData.xml","utf8"),"CLight");assert.ok(light.list().find(n=>n.id==="AgriaNight"));});
test("native attribute/child encodings and implicit zero state survive lighting edits",()=>{const source='<Catalog><CLight id="A"><ToDInfoArray><AmbientColor value="0,0,0"/><DirectionalLight index="Key" Color="1,1,1"/></ToDInfoArray><ToDInfoArray index="1" AmbientColor="1,0,0"/></CLight></Catalog>';const next=new LightingCatalog(source,"CLight").patch({id:"A",ambientColor:[0.1,0.2,0.3],directional:[{index:"Key",intensity:2,color:[0.2,0.3,0.4]}]});assert.match(next,/<AmbientColor value="0.1,0.2,0.3"/);assert.match(next,/Color="0.2,0.3,0.4"/);assert.match(next,/ColorMultiplier="2"/);assert.match(next,/<ToDInfoArray index="1" AmbientColor="1,0,0"\/>/);assert.throws(()=>new LightingCatalog('<Catalog><CLight id="A"><ToDInfoArray/><ToDInfoArray index="0"/></CLight></Catalog>',"CLight").patch({id:"A",exposure:1}),/AMBIGUOUS/);});
test("isolated preset and map assignment stage/save atomically without height changes",async()=>{const f=await fixture();try{const heights=await fs.readFile(path.join(f.root,"t3HeightMap"));const p=await f.terrain.plan({operations:[{op:"lighting.preset",id:"Night",parent:"Base",ambientColor:[0.1,0.2,0.4],exposure:1.2,directional:[{index:"Key",direction:[0,0,-1],intensity:0.4}]},{op:"lighting.assign",id:"Night"}]});assert.equal(p.valid,true);const a=await f.terrain.apply(p.id,{dryRun:false,stage:true});await assert.rejects(fs.readFile(path.join(f.root,"Base.SC2Data/GameData/TerrainData.xml")),/ENOENT/);await f.terrain.save(a.transaction!.transactionId!,{dryRun:false,backup:false});assert.deepEqual(await fs.readFile(path.join(f.root,"t3HeightMap")),heights);assert.equal((await f.terrain.lighting()).localBinding?.lighting,"Night");assert.match(await fs.readFile(path.join(f.root,"Base.SC2Data/GameData.xml"),"utf8"),/LightData.xml/);assert.match(await fs.readFile(path.join(f.root,"ComponentList.SC2Components"),"utf8"),/Type="gada"/);}finally{await f.cleanup();}});
test("missing light and cyclic parents fail before writing; strict XML compiles",async()=>{const f=await fixture();try{await assert.rejects(f.terrain.plan({operations:[{op:"lighting.assign",id:"Missing"}]}),/DEPENDENCY_UNAVAILABLE/);await fs.writeFile(path.join(f.root,"Base.SC2Data/GameData/LightData.xml"),'<Catalog><CLight id="A" parent="B"/><CLight id="B" parent="A"/></Catalog>');await assert.rejects(f.terrain.plan({operations:[{op:"lighting.assign",id:"A"}]}),/PARENT_CYCLE/);const p=parseTerrainRecipe('<TerrainRecipe version="1"><LightingPreset id="Night" parent="Base" ambientColor="0.1,0.2,0.3" exposure="1.2"/><Lighting id="Night"/></TerrainRecipe>');assert.deepEqual(p.operations.map(o=>o.op),["lighting.preset","lighting.assign"]);assert.throws(()=>parseTerrainRecipe('<TerrainRecipe version="1"><Lighting id="Night" fake="1"/></TerrainRecipe>'),/UNKNOWN_RECIPE_ATTRIBUTE/);}finally{await f.cleanup();}});
test("landscape and lighting share one plan; external catalog edits invalidate a staged lighting save",async()=>{const f=await fixture();try{const {BrowseWorkspace}=await import("../modules/browse/workspace.js");const {DataWorkspace}=await import("../modules/data/workspace.js");const workspace=new Workspace(f.root);const terrain=new TerrainWorkspace(workspace,new BrowseWorkspace(workspace,new DataWorkspace(workspace)));const state=await terrain.state();const texture=state.descriptor.textures.find(t=>t.id)?.id;assert.ok(texture);const p=await terrain.landscape({style:"forest",area:{type:"rectangle",minX:8,minY:8,maxX:16,maxY:16},materials:{base:texture},lighting:"Base"});assert.ok(p.operations.some(o=>o.op==="height.noise"));assert.equal(p.operations.at(-1)?.op,"lighting.assign");const a=await terrain.apply(p.id,{dryRun:false,stage:true});const external=path.join(f.root,"Base.SC2Data/GameData/External.xml");await fs.writeFile(external,'<Catalog><CLight id="Other"/></Catalog>');await assert.rejects(terrain.save(a.transaction!.transactionId!,{dryRun:false,backup:false}),/STALE_WATER_DEPENDENCIES/);await fs.unlink(external);await terrain.save(a.transaction!.transactionId!,{dryRun:false,backup:false});assert.equal((await terrain.lighting()).localBinding?.lighting,"Base");}finally{await f.cleanup();}});

test("malformed lighting does not block height-only plans; landscape accepts omitted area",async()=>{const f=await fixture();try{await fs.writeFile(path.join(f.root,"Base.SC2Data/GameData/LightData.xml"),'<Catalog><CLight id="A" id="B"/></Catalog>');const p=await f.terrain.plan({operations:[{op:"height.set",area:{type:"rectangle",minX:8,minY:8,maxX:16,maxY:16},height:"currentMedian"}]});assert.equal(p.valid,true);await fs.writeFile(path.join(f.root,"Base.SC2Data/GameData/LightData.xml"),'<Catalog><CLight id="Base"/></Catalog>');const {BrowseWorkspace}=await import("../modules/browse/workspace.js");const {DataWorkspace}=await import("../modules/data/workspace.js");const workspace=new Workspace(f.root);const terrain=new TerrainWorkspace(workspace,new BrowseWorkspace(workspace,new DataWorkspace(workspace)));const state=await terrain.state();const texture=state.descriptor.textures.find(t=>t.id)?.id;assert.ok(texture);const landscape=await terrain.landscape({style:"forest",materials:{base:texture}});assert.equal(landscape.valid,true);}finally{await f.cleanup();}});
