import type { McpServer } from '@modelcontextprotocol/server';
import * as z from 'zod/v4';
import { ScriptWorkspace, scriptPlanSchema } from './workspace.js';
const file = z.string().min(1), name = z.string().regex(/^[A-Za-z_][A-Za-z_0-9]*$/), limit = z.number().int().min(1).max(500).default(50);
const result = (value: unknown) => ({ content: [{ type: 'text' as const, text: JSON.stringify(value) }] });
export function registerScriptTools(server: McpServer, s: ScriptWorkspace) {
    server.registerTool('script.inspect', { description: 'Read-only Galaxy index, file hashes, Includes, diagnostics, native provenance and bounded cache status. Not a target compiler.', inputSchema: z.object({}).strict() }, async () => result(await s.inspect()));
    server.registerTool('script.symbols', { description: 'Paginated function/prototype/global/struct signatures without full files.', inputSchema: z.object({ file: file.optional(), query: z.string().optional(), offset: z.number().int().min(0).default(0), limit }).strict() }, async (a) => result(await s.symbols(a)));
    server.registerTool('script.references', { description: 'Token references and exact string candidates; conservative evidence, not complete scope binding.', inputSchema: z.object({ name, limit }).strict() }, async (a) => result(await s.references(a.name, a.limit)));
    server.registerTool('script.context', { description: 'Bounded function source, local dependency signatures and pinned native signatures; exposes truncation/unresolved calls.', inputSchema: z.object({ file, name, maxChars: z.number().int().min(1000).max(64000).default(8000) }).strict() }, async (a) => result(await s.context(a)));
    server.registerTool('script.validate', { description: 'Lexical/structural diagnostics, Include safety and unresolved call index. Reports PARTIAL semantics and compiler NOT_EXECUTED.', inputSchema: z.object({}).strict() }, async () => result(await s.validate()));
    server.registerTool('script.plan', { description: 'Plan file creation, one-function addition, body patch, guarded static rename and Include/init connection. Preserves unknown source; no GUI trigger edits.', inputSchema: scriptPlanSchema }, async (a) => result(await s.plan(a)));
    server.registerTool('script.apply', { description: 'Dry-run diffs or stage a stale-guarded atomic Galaxy plan. Save explicitly after review.', inputSchema: z.object({ planId: z.string(), dryRun: z.boolean().default(true) }).strict() }, async (a) => result(await s.apply(a.planId, a.dryRun)));
    server.registerTool('script.connect', { description: 'Plan an Include and zero-argument void init call in an existing entry function. Does not invent a native map foundation.', inputSchema: z.object({ file, init: name, entryFile: file.default('MapScript.galaxy'), entry: name.default('InitMap') }).strict() }, async (a) => result(await s.plan({ operations: [{ op: 'connect', ...a }] })));
    server.registerTool('script.recipe', { description: 'Plan standalone init scaffold or periodic Galaxy callback around an existing void action. No GUI triggers; native calls require target validation.', inputSchema: z.object({ file, name, kind: z.enum(['init', 'periodic']), seconds: z.number().positive().max(86400).optional(), action: name.optional() }).strict() }, async (a) => result(await s.recipe(a)));
    server.registerTool('script.save', { description: 'Save the whole staged text group using shared stale guards and backups.', inputSchema: z.object({ file, backup: z.boolean().default(true) }).strict() }, async (a) => result(await s.save(a.file, a.backup)));
    server.registerTool('script.discard', { description: 'Discard the complete coupled staged text group.', inputSchema: z.object({ file }).strict() }, async (a) => result(s.discard(a.file)));
}
